base_model: microsoft/Phi-3-mini-4k-instruct
trust_remote_code: true
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
chat_template: phi_3
deepspeed: deepspeed_configs/zero1.json

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: verifiers-for-code/structured_ft_27k_phi3 
    type: completion
    field: text
    train_on_split: train

dataset_prepared_path:
output_dir: ./out/phi3-ft

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 256
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

gradient_accumulation_steps: 1
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_torch
adam_beta2: 0.95
adam_epsilon: 0.00001
max_grad_norm: 1.0
lr_scheduler: cosine
learning_rate: 5.0e-5
train_on_inputs: false
group_by_length: false
bf16: auto

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
logging_steps: 1
flash_attention: true


warmup_ratio: 0.05
debug: true
weight_decay: 0.1
resize_token_embeddings_to_32x: true